from collections.abc import Iterator

__version__: str

class PyTrie:
    def __init__(self, items: list[str] | None = None) -> None: ...
    def get(self, key: str) -> str | None: ...
    def get_or(self, key: str, default: str | None = None) -> str | None: ...
    def contains(self, key: str) -> bool: ...
    def starts_with(self, prefix: str) -> bool: ...
    def prefix_contains(self, prefix: str) -> bool: ...
    def insert(self, key: str, value: str) -> str | None: ...
    def add(self, key: str) -> str | None: ...
    def update(self, items: list[tuple[str, str]]) -> None: ...
    def remove(self, key: str) -> str | None: ...
    def discard(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def iter(self) -> PyTrieIterator: ...
    def prefix_search(self, prefix: str) -> PyTrieIterator: ...
    def longest_prefix(self, query: str) -> tuple[str, str] | None: ...
    def fuzzy_search(
        self, query: str, max_distance: int = 2, limit: int = 10
    ) -> list[tuple[str, str, int]]: ...
    def fuzzy_match(
        self, query: str, max_distance: int = 2
    ) -> tuple[str, str, int] | None: ...
    def freeze(self) -> PyFrozenTrie: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> PyTrieIterator: ...

class PyTrieIterator(Iterator[tuple[str, str]]):
    def __iter__(self) -> PyTrieIterator: ...
    def __next__(self) -> tuple[str, str]: ...

class PyFrozenTrie:
    def get(self, key: str) -> str | None: ...
    def get_or(self, key: str, default: str | None = None) -> str | None: ...
    def contains(self, key: str) -> bool: ...
    def starts_with(self, prefix: str) -> bool: ...
    def prefix_contains(self, prefix: str) -> bool: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def iter(self) -> PyTrieIterator: ...
    def prefix_search(self, prefix: str) -> PyTrieIterator: ...
    def longest_prefix(self, query: str) -> tuple[str, str] | None: ...
    def fuzzy_search(
        self, query: str, max_distance: int = 2, limit: int = 10
    ) -> list[tuple[str, str, int]]: ...
    def fuzzy_match(
        self, query: str, max_distance: int = 2
    ) -> tuple[str, str, int] | None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> str: ...
    def __iter__(self) -> PyTrieIterator: ...
